apiVersion: v1
kind: ConfigMap
metadata:
  name: cafeflow-product-config
  namespace: cafeflow
data:
  NODE_ENV: "production"
  PORT: "4000"
  CORS_ORIGIN: "*"
  GRAPHQL_INTROSPECTION: "true"
  LOG_LEVEL: "info"
  LOW_STOCK_THRESHOLD: "5"
