apiVersion: v1
kind: Service
metadata:
  name: cafeflow-product-service
  namespace: cafeflow
spec:
  selector:
    app: cafeflow-product-service
  ports:
    - name: http
      port: 4000
      targetPort: http
  type: ClusterIP
